### PR TITLE
Add input-id to input props

### PR DESCRIPTION
**Pull request by bryansamuel1**
In order to use vee-validate it selects elements via id which was not present on the input.

### CODE REVIEW

**Comment by mengxiong10** [comment]
Thanks for PR.
I'd like use an object property(input-attr) for the input attr.
So I will delete those properties(eg: input-name) in a future version.
You can do this now.
```html

<date-picker ref="picker"></date-picker>

```
```js
  mounted () {
    const datePicker = this.$refs.base
    const input = datePicker.$refs.input
    input.setAttribute('id', 'yourId')
  }

```

**Comment by bryansamuel1** [comment]
`<date-picker ref="picker"></date-picker>`

Did you mean $refs.picker instead of $refs.base?
```
  mounted () {
    const datePicker = this.$refs.picker
    const input = datePicker.$refs.input
    input.setAttribute('id', 'yourId')
  }
```

**Comment by mengxiong10** [comment]
Yes

**Comment by warlord0** [comment]
> On a related note. Vee-Validate needs the input to have a unique ref, not "input". If I changed the ref="input" on the input element to :ref="inputProps" and pass a unique ref down, would that cause likely issues with the functionality of date-picker?

No because the scope of .input is different in each of your datepicker components

```javascript
    const datePicker = this.$refs.picker1
    const input = datePicker.$refs.input
    input.setAttribute('id', 'yourId')
    ...
   const datePicker = this.$refs.picker2
   /* So this.$refs.picker1.input !== this.$refs.picker2.input */
```

**Comment by mengxiong10** [comment]
#173

**Comment by mengxiong10** [comment]
<date-picker :input-attr="{id:'input'}" />

**Comment by mengxiong10** [comment]
<date-picker :input-attr="{id:'input'}" />

**Pull request closed without merging**
