### PR TITLE
Added required attribute

### PR DESCRIPTION
**Pull request by koss-shtukert**

### CODE REVIEW

**Comment by akki-jat** [comment]
@mengxiong10 can you take a look at this request, I am also waiting for this change.

**Comment by mengxiong10** [comment]
@akki-jat 
```html
<date-picker v-model="time1" ref="datepicker"></date-picker>
```

```js
this.refs.datepicker.refs.input.required = true
```

**Comment by akki-jat** [comment]
@mengxiong10 thanks for solution. But what about when I am using multiple datepickers?

**Comment by mengxiong10** [comment]
@akki-jat 
use the different ref.
Or
```js
mounted () {
    [...document.querySelectorAll('.mx-input')].forEach(v => {
      v.required = true
    })
  }
```

**Comment by akki-jat** [comment]
@mengxiong10 second solution is good & I'm gonna use it. But I also thought it would be good to have required prop. What do you think?

And again thanks for solution & quick response.

**Comment by chumager** [comment]
Hi, Isn't simpler just add `:required="$attrs.required ? true : false" ` in the input???

**Comment by mengxiong10** [comment]
v2.7.0
Add a prop `input-attr` to achieve it like this.
```html
<date-picker :input-attr="{ required: true }" />

```

**Pull request closed without merging**
