### PR TITLE
Added confirm text as a prop

### PR DESCRIPTION
**Pull request by msonowal**

### CODE REVIEW

**Comment by mengxiong10** [comment]
you should delete the languages code, just retain the confirm-text prop(use kebab-case).  Others use this to set language local.

**Comment by msonowal** [comment]
@mengxiong10 I have removed the langauges code

**Comment by msonowal** [comment]
@mengxiong10  Can you tag a version with latest commit so that we can install

**Comment by mengxiong10** [comment]
@msonowal  I had published v1.6.1. the prop confirm text changed from confirm_text to confirm-text.

**Pull request merged**
