### PR TITLE
feat: add event keyup

### PR DESCRIPTION
**Pull request by MrBurrBurr**
I wanted to pass a vue method to the datepicker via the `inputAttr` property. Like this (pseudo code):

```html
<script>
  export default {
    methods: {
      myFunction() {
        console.log('myFunction was called')
      },
    },
  };
</script>

<template>
  <date-picker :inputAttr="{keyup: 'myFunction()'}"></date-picker>
</template>
```

This did not work as expected. It would not recognize my function, I guess since it's a different scope - I didn't bother to investigate.

Anyways, I just added a new event property called `@keyup` and so far it works as expected.

```html
<script>
  export default {
    methods: {
      myFunction() {
        console.log('myFunction was called')
      },
    },
  };
</script>

<template>
  <date-picker @keyup="myFunction()"></date-picker>
</template>
```

I didn't know how to add it to the unittest since I am not familiar with jester and since there are no contribution guidelines I guess it's this is acceptable, so bare with me.

### CODE REVIEW

**Comment by mengxiong10** [comment]
You can use event propagation.
```html
<date-picker  @keyup.native="handleKeyup" />

```

**Comment by MrBurrBurr** [comment]
This will sadly not work in my case.

**Comment by mengxiong10** [comment]
@MrBurrBurr You can use ref.
```html
<date-picker ref="datepicker" />
```
```js
mounted() {
  const input = this.$refs.datepicker.$refs.input;
  input.addEventListener('keyup', ...)
}


```

**Comment by MrBurrBurr** [comment]
Thank you for your help.

I guess this would work but it's much more code compared to my solution. I already published a new npm package with my changes and it works great!

Maybe at some point some other people will run into the same issue as me and it will be important enough for you to consider implementing it.

**Pull request closed without merging**
